language: php
dist: trusty
php:
  - '7.0'
  - '7.1'
  - '7.2'
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v
